"""Building Layout Guidance Agent — room sizes, ventilation, staircase, area definitions."""


def handle_building_layout(intent: str, params: dict) -> str:
    """Handle building layout and planning queries."""
    return _respond_building_planning()


def _respond_building_planning() -> str:
    return (
        "## Building Planning — Room Dimensions, Ventilation & Area Definitions\n\n"
        "### Quick Answer\n"
        "NBC 2016 (Part 4) defines minimum room sizes, ventilation requirements, "
        "and staircase dimensions. Window area must be ≥ 1/10th of floor area.\n\n"
        "### Why This Matters\n"
        "Building planning governs habitability, safety, and regulatory compliance. "
        "Non-compliant designs fail municipal approval and compromise occupant comfort.\n\n"
        "### Practical Recommendation\n\n"
        "**Minimum Room Dimensions (NBC 2016):**\n"
        "| Room | Min Area (sqm) | Min Width (m) | Min Height (m) |\n"
        "|---|---|---|---|\n"
        "| Living room | 9.5 | 2.4 | 2.75 |\n"
        "| Bedroom (master) | 9.5 | 2.7 | 2.75 |\n"
        "| Bedroom (other) | 7.5 | 2.1 | 2.75 |\n"
        "| Kitchen | 5.0 | 1.8 | 2.75 |\n"
        "| Kitchen + dining | 7.5 | 2.1 | 2.75 |\n"
        "| Bathroom | 1.8 | 1.2 | 2.2 |\n"
        "| WC (separate) | 1.1 | 0.9 | 2.2 |\n"
        "| Combined bath + WC | 2.8 | 1.2 | 2.2 |\n"
        "| Corridor (residential) | — | 1.0 | 2.4 |\n"
        "| Staircase width | — | 1.0 (residential) | — |\n\n"
        "### Staircase Design Rules\n"
        "• Riser (R): 150mm (recommended) | Max 190mm (residential)\n"
        "• Tread (T): 250mm (min) | 300mm (recommended)\n"
        "• Rule: 2R + T = 580–620mm\n"
        "• Flight width: min 1.0m (residential), 1.5m (public)\n"
        "• Max 15 risers per flight without landing\n"
        "• Headroom: min 2.2m at any point\n"
        "• Handrail height: 900–1000mm\n\n"
        "### Ventilation Requirements (NBC 2016)\n"
        "• Window area: min 1/10th of floor area (habitable rooms)\n"
        "• Kitchen: exhaust fan or chimney + window\n"
        "• Bathroom: min 0.3 sqm ventilation opening\n"
        "• Cross ventilation essential for tropical climate\n\n"
        "### Options / Comparisons\n"
        "**Area Definitions:**\n"
        "| Term | Definition |\n"
        "|---|---|\n"
        "| Carpet Area | Internal usable area (wall-to-wall, excluding walls) |\n"
        "| Built-up Area | Carpet area + wall thickness (~10–15% more) |\n"
        "| Super Built-up | Built-up + share of common areas (~25–40% more than carpet) |\n\n"
        "### Common Mistakes to Avoid\n"
        "- Not accounting for setback rules (reduces usable plot area)\n"
        "- Ignoring NBC minimum room sizes → municipal rejection\n"
        "- Placing kitchen/bathroom without proper ventilation openings\n"
        "- Staircase width less than 1m (unsafe, non-compliant)\n\n"
        "### Safety Note\n"
        "⚠️ All plans must comply with local DCR (Development Control Rules) "
        "which may have stricter requirements than NBC 2016.\n\n"
        "### Next Step\n"
        "Share your plot dimensions, setback requirements, and room count "
        "for a layout optimization suggestion.\n\n"
        "📋 *Veda — Nirmaan Civil Engineering Intelligence. Reference: NBC 2016 Part 4, local DCR.*"
    )
